### ISSUE TITLE
todo app

### ISSUE THREAD

**Issue by mrjjwright** [auto-lib/autojs#1]
This is awesome!  Do you have any examples of real world todo like things to see how this performs in the wild.  I currently use dipole https://github.com/zheksoon/dipole (S.js, Sinuous, SolidJS I have also considered as well as a long time Mobx user).  Also I am interested to hear or see how this has been successful for you and how you think reactivity can go bad easily.      If you answer zero of this, that is ok!   Thanks!

**Comment by mrjjwright** [comment]
How do you change state with auto?  

> ok the law of auto is this: each piece of global state is either 1. just a plain value which you can change how you please, or 2. a named function which cannot be changed directly but which the function itself solely determines the value of. doesn't sound so great when you lay it out like that...

**Comment by kewp** [comment]
Glad to hear you like it. Don't have any project examples. Not sure how that would look - I suppose I'd need to write examples for different popular libraries like React, Vue, etc. You can look at the tests to see how the library is used. Might need to read through the test readme to understand what you are looking at.

I'm busy using this for one of my work projects and it's working well. It seems to make things a lot easier to work with in general though I still have a way to go before I really push the library as the project gets more complex.

Why reactivity goes bad is a big question for me - I'm still figuring out how to talk about this. _How_ it goes bad is that things become impossible to debug. That is my experience and I have a lot of it in this case. Basically you cannot figure out what caused a variable to update. _Why_ this happens is because state updates can happen anywhere and at any time. The idea behind auto is to force a single variable-function relationship in your state and have a library do the updates automatically, but also enforcing this by not letting state change from any other source. Basically auto makes it impossible to write multi-aspect logic, if that makes sense.

**Comment by mrjjwright** [comment]
Thanks for the answer!   Yes, this is what I have found in working with these kinds of libraries as well,  occasionally something updates and you don't know why and also something doesn't update and you don't know why.   But far better than streams!   The way you built this library seems very effective, glad it's working for you!

**Comment by kewp** [comment]
Thanks for the feedback, nice to hear what I feel mirrored back.

**Comment by mrjjwright** [comment]
Are you using this lib with svelte?

**Comment by kewp** [comment]
Yes the project I'm working on now is using Svelte. I am using just one auto instance though there's no reason you can't use multiple. Also I've experimented with nested auto values which works too.
